spring:
  datasource:
    url: jdbc:postgresql://dpg-d3v37sili9vc73cgmnj0-a.oregon-postgres.render.com:5432/bistral-bistro-service
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8084
