# spring:
#   datasource:
#     url: jdbc:postgresql://dpg-d3v37sili9vc73cgmnj0-a.oregon-postgres.render.com:5432/bistral-order-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bistral_order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html



server:
  port: 8085
