# spring:
#   datasource:
#     url: jdbc:postgresql://dpg-d3v37sili9vc73cgmnj0-a.oregon-postgres.render.com:5432/bistral-order-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bistral-order-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver



server:
  port: 8085
